version: "3"
services:
  node:
    container_name: clean-architecture-example
    image: node:alpine
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir: /workspaces/clean-architecture-example/
    environment:
      NODE_NO_WARNINGS: "1"
      PORT: ${PORT:-8081}
    volumes:
      - ./:/workspaces/clean-architecture-example/
      - node_modules:/workspaces/biteship-sap-mvc/node_modules/
    external_links:
      - mongo
      - postgres
    networks:
      - biteship
    ports:
      - "8081:8081"
volumes:
  node_modules:
networks:
  biteship:
    name: biteship
    external: true
